services:
  - type: web
    name: novarsis-chatbot
    runtime: python-3.11
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn novars2:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: MONGODB_URL
        sync: false
      - key: OLLAMA_API_KEY
        sync: false
      - key: OLLAMA_BASE_URL
        value: https://ollama.com
      - key: OLLAMA_MODEL
        value: codellama:13b